<?php 
    require_once('head_html.php'); 
    require_once('../Includes/config.php'); 
    require_once('../Includes/session.php'); 
    require_once('../Includes/user.php'); 
    if ($logged==false) {
         header("Location:../index.php");
    }
?>


<body>

    <div id="wrapper">

       <?php 
            require_once("nav.php");
            require_once("sidebar.php");
        ?>


   
    
<div class="header1" style="border-width: 0px 0px 1px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-text-opacity: 1; color: rgba(55,65,81,var(--tw-text-opacity)); font-weight: 800; margin-bottom: 1.5rem; padding-bottom: 0.75rem; font-size: 1.875rem; line-height: 2.25rem; font-family: Nunito, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Digital Payment System another Option the Era Demands</div>
    <div style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; color: rgb(0, 0, 0); font-family: Nunito, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify; font-family: Nunito, Roboto, RobotoDraft, Helvetica, Arial, sans-serif;">Our era is the time of digitalization. Various sources indicate that an average of 62.5 percent of the world's population makes online transactions due to the high level of use of the digital economy system in the world.</p>
      <figure class="image image_resized image-style-align-right" style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin-top: 0px; margin-right: auto; margin-bottom: 0.9em; margin-left: var(--ck-image-style-spacing); clear: none; display: table; min-width: 50px; text-align: center; float: right; width: 450px;"></figure>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">The digital economy system plays an irreplaceable role in enabling a society to actively participate in the economic activities of the country. The importance of this technology in building a healthy economy by aligning market supply and demand is significant.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">In our country, Ethiopia, a plan called "Digital Ethiopia" is underway to digitize the service delivery of institutions by 2025. In recent years, digital marketing in Ethiopia has grown two or three times. Especially mobile marketing has shown great progress.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">A digital payment system means moving away from cash transactions to payment cards, electronic money, transferring money and making payments through modern technology such as automatic teller machines (ATMs), mobile phones, etc.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">The implementation of digital payment options will not only create transparency and efficiency, but also create a financial system in which the entire society can participate, and will bring many benefits in terms of realizing inclusive growth.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">The transition from cash to digital payments will reduce significant costs at the government level. By providing efficient services between individuals and institutions, it reduces time, energy, and costs, and improves the living conditions of citizens.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">In our country, Ethiopia, many institutions have already started activities that enable them to perform their operations with digital technology, and they are changing their services to a digital operating system.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">In this regard, Ethiopian Electricity Utility is updating the previous inefficient payment process by transferring the monthly utility payment system of post-paid meter customers to digital payment options.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">By improving the cash payment system that customers used to go to the Utility's service centers before, the post-payment meter customers have now enabled to pay their monthly electricity bills from where they are, through digital payment options such as Tele Birr, CBE Birr, Mobile Banking and Internet Banking.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">Therefore, at present, most of postpaid meter customers are making their payments using the digital payment options that are in use. In order to put this system into full operation at the Utility, customers of postpaid meters in Addis Ababa city have been made to pay their monthly electricity consumption bills through digital payment options since the beginning of May in the budget year.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">Similarly, customers across the country will be able to fully pay their bills through modern payment options from the beginning of next July.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">The fact that this payment system is easy to use, efficient, simple, transparent, free of cash transfer, time and energy saving, safe, and inclusive of all sections of society has a great importance for the Utility as well as customers.</p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;"> </p>
      <p style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; margin: 0px; text-align: justify;">Thus, customers spend less and use more when they use this smart payment option. They also update their daily life.<img src="http://www.ethiopianelectricutility.gov.et/lfm/1686569998.jpg" width="392" height="288" style="border-width: 0px; border-style: solid; border-color: rgba(229,231,235,var(--tw-border-opacity)); border-image: initial; box-sizing: border-box; --tw-border-opacity: 1; --tw-shadow: 0 0 #0000; --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/); --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,0.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; display: block; vertical-align: middle; height: auto; max-width: 100%; object-fit: contain; margin: 0px auto; min-width: 100%;" srcset="http://www.ethiopianelectricutility.gov.et/lfm/1686569998.jpg 800w, http://www.ethiopianelectricutility.gov.et/lfm/1686569998.jpg 1024w, http://www.ethiopianelectricutility.gov.et/lfm/1686569998.jpg 1920w" sizes="100vw"></p>
    </div>
</body>

</html>
<?php 
    
    require_once("js.php");
    ?>